/**
 * Complete USCIS Form I-130 (Petition for Alien Relative) Schema
 * Edition: 03/22/2023
 *
 * Based on the official USCIS I-130 form structure.
 * Each field includes a pdfField mapping to the AcroForm field name.
 * conditionalDisplay is used for fields that only appear based on prior answers.
 */

export const I130_SCHEMA = {
  formCode: 'I-130',
  parts: [
    // =============================================
    // PART 1: Relationship
    // =============================================
    {
      id: 'part1',
      title: 'Part 1. Relationship',
      translations: {
        es: { title: 'Parte 1. Relación' },
        pt: { title: 'Parte 1. Relacionamento' },
      },
      sections: [
        {
          id: 'relationship',
          title: 'Relationship',
          description: 'Select the relationship between {{petitioner.fullName}} (the petitioner) and {{beneficiary.fullName}} (the beneficiary).',
          fallbackDescription: 'Select the relationship between you (the petitioner) and the person you are filing for (the beneficiary).',
          translations: {
            es: {
              title: 'Relación',
              description: 'Selecciona la relación entre {{petitioner.fullName}} (el peticionario) y {{beneficiary.fullName}} (el beneficiario).',
              fallbackDescription: 'Selecciona la relación entre usted (el peticionario) y la persona para la que está presentando la solicitud (el beneficiario).',
            },
            pt: {
              title: 'Relacionamento',
              description: 'Selecione o relacionamento entre {{petitioner.fullName}} (o peticionário) e {{beneficiary.fullName}} (o beneficiário).',
              fallbackDescription: 'Selecione o relacionamento entre você (o peticionário) e a pessoa para quem está solicitando (o beneficiário).',
            },
          },
          fields: [
            {
              id: 'filingFor',
              type: 'radio',
              label: '{{petitioner.firstName}} is filing this petition for {{beneficiary.firstName}} who is {{petitioner.firstName}}\'s...',
              fallbackLabel: 'I am filing this petition for my...',
              nameInterpolation: true,
              required: true,
              options: [
                { value: 'spouse', label: 'Spouse' },
                { value: 'parent', label: 'Parent' },
                { value: 'brother_sister', label: 'Brother/Sister' },
                { value: 'child', label: 'Child' },
              ],
              pdfField: 'Pt1Line1_Relationship',
              translations: {
                es: {
                  label: '{{petitioner.firstName}} está presentando esta petición para {{beneficiary.firstName}} quien es {{petitioner.firstName}}...',
                  fallbackLabel: 'Estoy presentando esta petición para mi...',
                  options: {
                    spouse: 'Cónyuge',
                    parent: 'Padre/Madre',
                    brother_sister: 'Hermano/Hermana',
                    child: 'Hijo/Hija',
                  },
                },
                pt: {
                  label: '{{petitioner.firstName}} está apresentando esta petição para {{beneficiary.firstName}} que é {{petitioner.firstName}}...',
                  fallbackLabel: 'Estou apresentando esta petição para meu...',
                  options: {
                    spouse: 'Cônjuge',
                    parent: 'Pai/Mãe',
                    brother_sister: 'Irmão/Irmã',
                    child: 'Filho/Filha',
                  },
                },
              },
            },
            {
              id: 'childAdopted',
              type: 'radio',
              label: 'Was {{beneficiary.firstName}} adopted?',
              fallbackLabel: 'If you are filing for a child, was the child adopted?',
              nameInterpolation: true,
              required: false,
              options: [
                { value: 'yes', label: 'Yes' },
                { value: 'no', label: 'No' },
              ],
              pdfField: 'Pt1Line2_ChildAdopted',
              conditionalDisplay: {
                field: 'part1.relationship.filingFor',
                value: 'child',
              },
              translations: {
                es: {
                  label: '¿Fue {{beneficiary.firstName}} adoptado(a)?',
                  fallbackLabel: 'Si está solicitando para un hijo, ¿fue el hijo adoptado?',
                  options: {
                    yes: 'Sí',
                    no: 'No',
                  },
                },
                pt: {
                  label: '{{beneficiary.firstName}} foi adotado(a)?',
                  fallbackLabel: 'Se você está solicitando para uma criança, a criança foi adotada?',
                  options: {
                    yes: 'Sim',
                    no: 'Não',
                  },
                },
              },
            },
            {
              id: 'siblingStepOrAdoptive',
              type: 'radio',
              label: 'Are {{petitioner.firstName}} and {{beneficiary.firstName}} related by a stepparent or adoptive parent?',
              fallbackLabel: 'Are you related by a stepparent or adoptive parent?',
              nameInterpolation: true,
              required: false,
              options: [
                { value: 'yes', label: 'Yes' },
                { value: 'no', label: 'No' },
              ],
              pdfField: 'Pt1Line3_SiblingStep',
              conditionalDisplay: {
                field: 'part1.relationship.filingFor',
                value: 'brother_sister',
              },
              translations: {
                es: {
                  label: '¿Están {{petitioner.firstName}} y {{beneficiary.firstName}} relacionados por un padrastro/madrastra o padre/madre adoptivo?',
                  fallbackLabel: '¿Están ustedes relacionados por un padrastro/madrastra o padre/madre adoptivo?',
                  options: {
                    yes: 'Sí',
                    no: 'No',
                  },
                },
                pt: {
                  label: '{{petitioner.firstName}} e {{beneficiary.firstName}} estão relacionados por um padrasto/madrasta ou pai/mãe adotivo?',
                  fallbackLabel: 'Vocês estão relacionados por um padrasto/madrasta ou pai/mãe adotivo?',
                  options: {
                    yes: 'Sim',
                    no: 'Não',
                  },
                },
              },
            },
            {
              id: 'multipleFilings',
              type: 'radio',
              label: 'Is {{petitioner.firstName}} filing this petition for more than one beneficiary?',
              fallbackLabel: 'Are you filing this petition for more than one beneficiary?',
              nameInterpolation: true,
              required: true,
              helpText: '{{petitioner.firstName}} must file a separate Form I-130 for each beneficiary.',
              fallbackHelpText: 'You must file a separate Form I-130 for each beneficiary.',
              options: [
                { value: 'yes', label: 'Yes' },
                { value: 'no', label: 'No' },
              ],
              pdfField: 'Pt1Line4_MultipleBeneficiaries',
              translations: {
                es: {
                  label: '¿Está {{petitioner.firstName}} presentando esta petición para más de un beneficiario?',
                  fallbackLabel: '¿Está usted presentando esta petición para más de un beneficiario?',
                  helpText: '{{petitioner.firstName}} debe presentar un Formulario I-130 separado para cada beneficiario.',
                  fallbackHelpText: 'Usted debe presentar un Formulario I-130 separado para cada beneficiario.',
                  options: {
                    yes: 'Sí',
                    no: 'No',
                  },
                },
                pt: {
                  label: '{{petitioner.firstName}} está apresentando esta petição para mais de um beneficiário?',
                  fallbackLabel: 'Você está apresentando esta petição para mais de um beneficiário?',
                  helpText: '{{petitioner.firstName}} deve apresentar um Formulário I-130 separado para cada beneficiário.',
                  fallbackHelpText: 'Você deve apresentar um Formulário I-130 separado para cada beneficiário.',
                  options: {
                    yes: 'Sim',
                    no: 'Não',
                  },
                },
              },
            },
          ],
        },
      ],
    },

    // =============================================
    // PART 2: Information About You (Petitioner)
    // =============================================
    {
      id: 'part2',
      title: 'Part 2. Information About {{petitioner.firstName}} (Petitioner)',
      translations: {
        es: { title: 'Parte 2. Información Sobre {{petitioner.firstName}} (Peticionario)' },
        pt: { title: 'Parte 2. Informações Sobre {{petitioner.firstName}} (Peticionário)' },
      },
      fallbackTitle: 'Part 2. Information About You',
      sections: [
        {
          id: 'names',
          title: '{{petitioner.firstName}}\'s Full Legal Name',
          fallbackTitle: 'Your Full Legal Name',
          fields: [
            {
              id: 'familyName',
              type: 'text',
              label: 'Family Name (Last Name)',
              required: true,
              maxLength: 33,
              pdfField: 'Pt2Line1a_FamilyName',
            },
            {
              id: 'givenName',
              type: 'text',
              label: 'Given Name (First Name)',
              required: true,
              maxLength: 33,
              pdfField: 'Pt2Line1b_GivenName',
            },
            {
              id: 'middleName',
              type: 'text',
              label: 'Middle Name',
              required: false,
              maxLength: 33,
              pdfField: 'Pt2Line1c_MiddleName',
            },
          ],
        },
        {
          id: 'otherNames',
          title: 'Other Names Used by {{petitioner.firstName}}',
          fallbackTitle: 'Other Names Used',
          description: 'Provide all other names {{petitioner.firstName}} has ever used, including aliases, maiden name, and nicknames.',
          fallbackDescription: 'Provide all other names you have ever used, including aliases, maiden name, and nicknames.',
          fields: [
            {
              id: 'maidenFamilyName',
              type: 'text',
              label: 'Family Name (Last Name) at Birth',
              required: false,
              maxLength: 33,
              pdfField: 'Pt2Line2a_MaidenFamilyName',
            },
            {
              id: 'maidenGivenName',
              type: 'text',
              label: 'Given Name (First Name) at Birth',
              required: false,
              maxLength: 33,
              pdfField: 'Pt2Line2b_MaidenGivenName',
            },
            {
              id: 'maidenMiddleName',
              type: 'text',
              label: 'Middle Name at Birth',
              required: false,
              maxLength: 33,
              pdfField: 'Pt2Line2c_MaidenMiddleName',
            },
          ],
        },
        {
          id: 'identifiers',
          title: 'Identification Numbers',
          fields: [
            {
              id: 'alienNumber',
              type: 'alien_number',
              label: 'Alien Registration Number (A-Number)',
              required: false,
              helpText: 'If you have an A-Number, enter it here. This is a 7 to 9-digit number.',
              pdfField: 'Pt2Line3_AlienNumber',
            },
            {
              id: 'uscisAccountNumber',
              type: 'text',
              label: 'USCIS Online Account Number',
              required: false,
              maxLength: 12,
              helpText: 'If you have previously filed an application or petition with USCIS online.',
              pdfField: 'Pt2Line4_USCISAccountNumber',
            },
            {
              id: 'ssn',
              type: 'ssn',
              label: 'U.S. Social Security Number',
              required: false,
              pdfField: 'Pt2Line5_SSN',
            },
          ],
        },
        {
          id: 'mailingAddress',
          title: '{{petitioner.firstName}}\'s Mailing Address',
          fallbackTitle: 'Your Mailing Address',
          fields: [
            {
              id: 'inCareOf',
              type: 'text',
              label: 'In Care Of Name',
              required: false,
              maxLength: 45,
              pdfField: 'Pt2Line6_InCareOf',
            },
            {
              id: 'streetNumber',
              type: 'text',
              label: 'Street Number and Name',
              required: true,
              maxLength: 45,
              pdfField: 'Pt2Line6a_StreetNumber',
            },
            {
              id: 'aptType',
              type: 'select',
              label: 'Apt/Ste/Flr',
              required: false,
              options: [
                { value: 'apt', label: 'Apt.' },
                { value: 'ste', label: 'Ste.' },
                { value: 'flr', label: 'Flr.' },
              ],
              pdfField: 'Pt2Line6b_Unit',
            },
            {
              id: 'aptNumber',
              type: 'text',
              label: 'Number',
              required: false,
              maxLength: 10,
              pdfField: 'Pt2Line6b_Number',
            },
            {
              id: 'city',
              type: 'text',
              label: 'City or Town',
              required: true,
              maxLength: 20,
              pdfField: 'Pt2Line6c_City',
            },
            {
              id: 'state',
              type: 'select',
              label: 'State',
              required: false,
              options: [
                { value: 'AL', label: 'Alabama' }, { value: 'AK', label: 'Alaska' },
                { value: 'AZ', label: 'Arizona' }, { value: 'AR', label: 'Arkansas' },
                { value: 'CA', label: 'California' }, { value: 'CO', label: 'Colorado' },
                { value: 'CT', label: 'Connecticut' }, { value: 'DE', label: 'Delaware' },
                { value: 'FL', label: 'Florida' }, { value: 'GA', label: 'Georgia' },
                { value: 'HI', label: 'Hawaii' }, { value: 'ID', label: 'Idaho' },
                { value: 'IL', label: 'Illinois' }, { value: 'IN', label: 'Indiana' },
                { value: 'IA', label: 'Iowa' }, { value: 'KS', label: 'Kansas' },
                { value: 'KY', label: 'Kentucky' }, { value: 'LA', label: 'Louisiana' },
                { value: 'ME', label: 'Maine' }, { value: 'MD', label: 'Maryland' },
                { value: 'MA', label: 'Massachusetts' }, { value: 'MI', label: 'Michigan' },
                { value: 'MN', label: 'Minnesota' }, { value: 'MS', label: 'Mississippi' },
                { value: 'MO', label: 'Missouri' }, { value: 'MT', label: 'Montana' },
                { value: 'NE', label: 'Nebraska' }, { value: 'NV', label: 'Nevada' },
                { value: 'NH', label: 'New Hampshire' }, { value: 'NJ', label: 'New Jersey' },
                { value: 'NM', label: 'New Mexico' }, { value: 'NY', label: 'New York' },
                { value: 'NC', label: 'North Carolina' }, { value: 'ND', label: 'North Dakota' },
                { value: 'OH', label: 'Ohio' }, { value: 'OK', label: 'Oklahoma' },
                { value: 'OR', label: 'Oregon' }, { value: 'PA', label: 'Pennsylvania' },
                { value: 'RI', label: 'Rhode Island' }, { value: 'SC', label: 'South Carolina' },
                { value: 'SD', label: 'South Dakota' }, { value: 'TN', label: 'Tennessee' },
                { value: 'TX', label: 'Texas' }, { value: 'UT', label: 'Utah' },
                { value: 'VT', label: 'Vermont' }, { value: 'VA', label: 'Virginia' },
                { value: 'WA', label: 'Washington' }, { value: 'WV', label: 'West Virginia' },
                { value: 'WI', label: 'Wisconsin' }, { value: 'WY', label: 'Wyoming' },
                { value: 'DC', label: 'District of Columbia' },
              ],
              pdfField: 'Pt2Line6d_State',
            },
            {
              id: 'zipCode',
              type: 'text',
              label: 'ZIP Code',
              required: false,
              maxLength: 10,
              pdfField: 'Pt2Line6e_ZipCode',
            },
            {
              id: 'province',
              type: 'text',
              label: 'Province',
              required: false,
              maxLength: 20,
              pdfField: 'Pt2Line6f_Province',
            },
            {
              id: 'postalCode',
              type: 'text',
              label: 'Postal Code',
              required: false,
              maxLength: 10,
              pdfField: 'Pt2Line6g_PostalCode',
            },
            {
              id: 'country',
              type: 'text',
              label: 'Country',
              required: true,
              maxLength: 30,
              pdfField: 'Pt2Line6h_Country',
            },
          ],
        },
        {
          id: 'physicalAddress',
          title: '{{petitioner.firstName}}\'s Physical Address',
          fallbackTitle: 'Your Physical Address',
          description: 'If {{petitioner.firstName}}\'s physical address is the same as the mailing address, select "Yes" below.',
          fallbackDescription: 'If your physical address is the same as your mailing address, select "Yes" below.',
          fields: [
            {
              id: 'sameAsMailingAddress',
              type: 'radio',
              label: 'Is {{petitioner.firstName}}\'s physical address the same as the mailing address?',
              fallbackLabel: 'Is your physical address the same as your mailing address?',
              nameInterpolation: true,
              required: true,
              options: [
                { value: 'yes', label: 'Yes' },
                { value: 'no', label: 'No' },
              ],
              pdfField: 'Pt2Line7_SameAddress',
            },
            {
              id: 'physStreetNumber',
              type: 'text',
              label: 'Street Number and Name',
              required: false,
              maxLength: 45,
              pdfField: 'Pt2Line7a_PhysStreetNumber',
              conditionalDisplay: {
                field: 'part2.physicalAddress.sameAsMailingAddress',
                value: 'no',
              },
            },
            {
              id: 'physAptType',
              type: 'select',
              label: 'Apt/Ste/Flr',
              required: false,
              options: [
                { value: 'apt', label: 'Apt.' },
                { value: 'ste', label: 'Ste.' },
                { value: 'flr', label: 'Flr.' },
              ],
              pdfField: 'Pt2Line7b_PhysUnit',
              conditionalDisplay: {
                field: 'part2.physicalAddress.sameAsMailingAddress',
                value: 'no',
              },
            },
            {
              id: 'physAptNumber',
              type: 'text',
              label: 'Number',
              required: false,
              maxLength: 10,
              pdfField: 'Pt2Line7b_PhysNumber',
              conditionalDisplay: {
                field: 'part2.physicalAddress.sameAsMailingAddress',
                value: 'no',
              },
            },
            {
              id: 'physCity',
              type: 'text',
              label: 'City or Town',
              required: false,
              maxLength: 20,
              pdfField: 'Pt2Line7c_PhysCity',
              conditionalDisplay: {
                field: 'part2.physicalAddress.sameAsMailingAddress',
                value: 'no',
              },
            },
            {
              id: 'physState',
              type: 'text',
              label: 'State',
              required: false,
              maxLength: 20,
              pdfField: 'Pt2Line7d_PhysState',
              conditionalDisplay: {
                field: 'part2.physicalAddress.sameAsMailingAddress',
                value: 'no',
              },
            },
            {
              id: 'physZipCode',
              type: 'text',
              label: 'ZIP Code',
              required: false,
              maxLength: 10,
              pdfField: 'Pt2Line7e_PhysZipCode',
              conditionalDisplay: {
                field: 'part2.physicalAddress.sameAsMailingAddress',
                value: 'no',
              },
            },
            {
              id: 'physProvince',
              type: 'text',
              label: 'Province',
              required: false,
              maxLength: 20,
              pdfField: 'Pt2Line7f_PhysProvince',
              conditionalDisplay: {
                field: 'part2.physicalAddress.sameAsMailingAddress',
                value: 'no',
              },
            },
            {
              id: 'physCountry',
              type: 'text',
              label: 'Country',
              required: false,
              maxLength: 30,
              pdfField: 'Pt2Line7h_PhysCountry',
              conditionalDisplay: {
                field: 'part2.physicalAddress.sameAsMailingAddress',
                value: 'no',
              },
            },
          ],
        },
        {
          id: 'personalInfo',
          title: 'Other Personal Information',
          fields: [
            {
              id: 'dateOfBirth',
              type: 'date',
              label: 'Date of Birth',
              required: true,
              pdfField: 'Pt2Line8_DateOfBirth',
            },
            {
              id: 'cityOfBirth',
              type: 'text',
              label: 'City/Town/Village of Birth',
              required: true,
              maxLength: 20,
              pdfField: 'Pt2Line9_CityOfBirth',
            },
            {
              id: 'countryOfBirth',
              type: 'text',
              label: 'Country of Birth',
              required: true,
              pdfField: 'Pt2Line10_CountryOfBirth',
            },
            {
              id: 'citizenship',
              type: 'text',
              label: 'Country of Citizenship or Nationality',
              required: true,
              pdfField: 'Pt2Line11_Citizenship',
            },
            {
              id: 'immigrationStatus',
              type: 'radio',
              label: 'I am a...',
              required: true,
              options: [
                { value: 'us_citizen', label: 'U.S. Citizen (by birth or naturalization)' },
                { value: 'lpr', label: 'Lawful Permanent Resident (LPR)' },
              ],
              pdfField: 'Pt2Line13_ImmigrationStatus',
            },
            {
              id: 'lprClassOfAdmission',
              type: 'text',
              label: 'Class of Admission',
              required: false,
              helpText: 'e.g., IR1, F2A, EB-2, DV',
              pdfField: 'Pt2Line14a_ClassOfAdmission',
              conditionalDisplay: {
                field: 'part2.personalInfo.immigrationStatus',
                value: 'lpr',
              },
            },
            {
              id: 'lprDateOfAdmission',
              type: 'date',
              label: 'Date of Admission as LPR',
              required: false,
              pdfField: 'Pt2Line14b_DateOfAdmission',
              conditionalDisplay: {
                field: 'part2.personalInfo.immigrationStatus',
                value: 'lpr',
              },
            },
          ],
        },
        {
          id: 'maritalInfo',
          title: 'Marital Information',
          fields: [
            {
              id: 'maritalStatus',
              type: 'select',
              label: 'Current Marital Status',
              required: true,
              options: [
                { value: 'single', label: 'Single, Never Married' },
                { value: 'married', label: 'Married' },
                { value: 'divorced', label: 'Divorced' },
                { value: 'widowed', label: 'Widowed' },
                { value: 'separated', label: 'Legally Separated' },
                { value: 'annulled', label: 'Marriage Annulled' },
              ],
              pdfField: 'Pt2Line15_MaritalStatus',
            },
            {
              id: 'timesMarried',
              type: 'number',
              label: 'How many times have you been married?',
              required: true,
              pdfField: 'Pt2Line16_TimesMarried',
            },
            {
              id: 'spouseFamilyName',
              type: 'text',
              label: 'Current Spouse\'s Family Name (Last Name)',
              required: false,
              maxLength: 33,
              pdfField: 'Pt2Line17a_SpouseFamilyName',
              conditionalDisplay: {
                field: 'part2.maritalInfo.maritalStatus',
                value: 'married',
              },
            },
            {
              id: 'spouseGivenName',
              type: 'text',
              label: 'Current Spouse\'s Given Name (First Name)',
              required: false,
              maxLength: 33,
              pdfField: 'Pt2Line17b_SpouseGivenName',
              conditionalDisplay: {
                field: 'part2.maritalInfo.maritalStatus',
                value: 'married',
              },
            },
            {
              id: 'spouseDateOfBirth',
              type: 'date',
              label: 'Current Spouse\'s Date of Birth',
              required: false,
              pdfField: 'Pt2Line18_SpouseDOB',
              conditionalDisplay: {
                field: 'part2.maritalInfo.maritalStatus',
                value: 'married',
              },
            },
            {
              id: 'dateOfMarriage',
              type: 'date',
              label: 'Date of Current Marriage',
              required: false,
              pdfField: 'Pt2Line19_DateOfMarriage',
              conditionalDisplay: {
                field: 'part2.maritalInfo.maritalStatus',
                value: 'married',
              },
            },
            {
              id: 'cityOfMarriage',
              type: 'text',
              label: 'City/Town of Current Marriage',
              required: false,
              maxLength: 20,
              pdfField: 'Pt2Line20a_CityOfMarriage',
              conditionalDisplay: {
                field: 'part2.maritalInfo.maritalStatus',
                value: 'married',
              },
            },
            {
              id: 'stateOfMarriage',
              type: 'text',
              label: 'State/Province of Current Marriage',
              required: false,
              maxLength: 20,
              pdfField: 'Pt2Line20b_StateOfMarriage',
              conditionalDisplay: {
                field: 'part2.maritalInfo.maritalStatus',
                value: 'married',
              },
            },
            {
              id: 'countryOfMarriage',
              type: 'text',
              label: 'Country of Current Marriage',
              required: false,
              maxLength: 30,
              pdfField: 'Pt2Line20c_CountryOfMarriage',
              conditionalDisplay: {
                field: 'part2.maritalInfo.maritalStatus',
                value: 'married',
              },
            },
          ],
        },
        {
          id: 'parentInfo',
          title: 'Parent Information',
          fields: [
            {
              id: 'parentUsCitizen',
              type: 'radio',
              label: 'Was your parent a U.S. citizen at the time you obtained permanent residence?',
              required: false,
              options: [
                { value: 'yes', label: 'Yes' },
                { value: 'no', label: 'No' },
                { value: 'na', label: 'Not applicable' },
              ],
              pdfField: 'Pt2Line21_ParentUSCitizen',
            },
          ],
        },
      ],
    },

    // =============================================
    // PART 3: Biographic Information (Petitioner)
    // =============================================
    {
      id: 'part3',
      title: 'Part 3. Biographic Information',
      sections: [
        {
          id: 'biographic',
          title: 'Biographic Information',
          description: 'Provide the following biographic information about {{petitioner.firstName}}.',
          fallbackDescription: 'Provide the following information about yourself.',
          fields: [
            {
              id: 'ethnicity',
              type: 'radio',
              label: 'Ethnicity (Select one)',
              required: true,
              options: [
                { value: 'hispanic_latino', label: 'Hispanic or Latino' },
                { value: 'not_hispanic_latino', label: 'Not Hispanic or Latino' },
              ],
              pdfField: 'Pt3Line1_Ethnicity',
            },
            {
              id: 'race',
              type: 'checkbox_group',
              label: 'Race (Select all applicable)',
              required: true,
              options: [
                { value: 'white', label: 'White' },
                { value: 'asian', label: 'Asian' },
                { value: 'black', label: 'Black or African American' },
                { value: 'american_indian', label: 'American Indian or Alaska Native' },
                { value: 'native_hawaiian', label: 'Native Hawaiian or Other Pacific Islander' },
              ],
              pdfField: 'Pt3Line2_Race',
            },
            {
              id: 'heightFeet',
              type: 'number',
              label: 'Height (Feet)',
              required: true,
              pdfField: 'Pt3Line3a_HeightFeet',
            },
            {
              id: 'heightInches',
              type: 'number',
              label: 'Height (Inches)',
              required: true,
              pdfField: 'Pt3Line3b_HeightInches',
            },
            {
              id: 'weight',
              type: 'number',
              label: 'Weight (Pounds)',
              required: true,
              pdfField: 'Pt3Line4_Weight',
            },
            {
              id: 'eyeColor',
              type: 'select',
              label: 'Eye Color',
              required: true,
              options: [
                { value: 'black', label: 'Black' },
                { value: 'blue', label: 'Blue' },
                { value: 'brown', label: 'Brown' },
                { value: 'gray', label: 'Gray' },
                { value: 'green', label: 'Green' },
                { value: 'hazel', label: 'Hazel' },
                { value: 'maroon', label: 'Maroon' },
                { value: 'pink', label: 'Pink' },
                { value: 'unknown', label: 'Unknown/Other' },
              ],
              pdfField: 'Pt3Line5_EyeColor',
            },
            {
              id: 'hairColor',
              type: 'select',
              label: 'Hair Color',
              required: true,
              options: [
                { value: 'bald', label: 'Bald (No hair)' },
                { value: 'black', label: 'Black' },
                { value: 'blond', label: 'Blond' },
                { value: 'brown', label: 'Brown' },
                { value: 'gray', label: 'Gray' },
                { value: 'red', label: 'Red' },
                { value: 'sandy', label: 'Sandy' },
                { value: 'white', label: 'White' },
                { value: 'unknown', label: 'Unknown/Other' },
              ],
              pdfField: 'Pt3Line6_HairColor',
            },
          ],
        },
      ],
    },

    // =============================================
    // PART 4: Information About Beneficiary
    // =============================================
    {
      id: 'part4',
      title: 'Part 4. Information About {{beneficiary.firstName}} (Beneficiary)',
      fallbackTitle: 'Part 4. Information About Beneficiary',
      sections: [
        {
          id: 'names',
          title: '{{beneficiary.firstName}}\'s Full Legal Name',
          fallbackTitle: 'Beneficiary\'s Full Legal Name',
          fields: [
            {
              id: 'familyName',
              type: 'text',
              label: 'Family Name (Last Name)',
              required: true,
              maxLength: 33,
              pdfField: 'Pt4Line1a_FamilyName',
            },
            {
              id: 'givenName',
              type: 'text',
              label: 'Given Name (First Name)',
              required: true,
              maxLength: 33,
              pdfField: 'Pt4Line1b_GivenName',
            },
            {
              id: 'middleName',
              type: 'text',
              label: 'Middle Name',
              required: false,
              maxLength: 33,
              pdfField: 'Pt4Line1c_MiddleName',
            },
          ],
        },
        {
          id: 'otherNames',
          title: 'Other Names Used by {{beneficiary.firstName}}',
          fallbackTitle: 'Other Names Used by Beneficiary',
          fields: [
            {
              id: 'otherFamilyName',
              type: 'text',
              label: 'Family Name (Last Name) at Birth',
              required: false,
              maxLength: 33,
              pdfField: 'Pt4Line2a_OtherFamilyName',
            },
            {
              id: 'otherGivenName',
              type: 'text',
              label: 'Given Name (First Name) at Birth',
              required: false,
              maxLength: 33,
              pdfField: 'Pt4Line2b_OtherGivenName',
            },
            {
              id: 'otherMiddleName',
              type: 'text',
              label: 'Middle Name at Birth',
              required: false,
              maxLength: 33,
              pdfField: 'Pt4Line2c_OtherMiddleName',
            },
          ],
        },
        {
          id: 'identifiers',
          title: '{{beneficiary.firstName}}\'s Identification Numbers',
          fallbackTitle: 'Beneficiary\'s Identification Numbers',
          fields: [
            {
              id: 'alienNumber',
              type: 'alien_number',
              label: 'Alien Registration Number (A-Number)',
              required: false,
              pdfField: 'Pt4Line3_AlienNumber',
            },
            {
              id: 'uscisAccountNumber',
              type: 'text',
              label: 'USCIS Online Account Number',
              required: false,
              maxLength: 12,
              pdfField: 'Pt4Line4_USCISAccountNumber',
            },
            {
              id: 'ssn',
              type: 'ssn',
              label: 'U.S. Social Security Number (if any)',
              required: false,
              pdfField: 'Pt4Line5_SSN',
            },
          ],
        },
        {
          id: 'mailingAddress',
          title: '{{beneficiary.firstName}}\'s Mailing Address',
          fallbackTitle: 'Beneficiary\'s Mailing Address',
          fields: [
            {
              id: 'inCareOf',
              type: 'text',
              label: 'In Care Of Name',
              required: false,
              maxLength: 45,
              pdfField: 'Pt4Line7_InCareOf',
            },
            {
              id: 'streetNumber',
              type: 'text',
              label: 'Street Number and Name',
              required: true,
              maxLength: 45,
              pdfField: 'Pt4Line7a_StreetNumber',
            },
            {
              id: 'aptType',
              type: 'select',
              label: 'Apt/Ste/Flr',
              required: false,
              options: [
                { value: 'apt', label: 'Apt.' },
                { value: 'ste', label: 'Ste.' },
                { value: 'flr', label: 'Flr.' },
              ],
              pdfField: 'Pt4Line7b_Unit',
            },
            {
              id: 'aptNumber',
              type: 'text',
              label: 'Number',
              required: false,
              maxLength: 10,
              pdfField: 'Pt4Line7b_Number',
            },
            {
              id: 'city',
              type: 'text',
              label: 'City or Town',
              required: true,
              maxLength: 20,
              pdfField: 'Pt4Line7c_City',
            },
            {
              id: 'state',
              type: 'text',
              label: 'State/Province',
              required: false,
              maxLength: 20,
              pdfField: 'Pt4Line7d_State',
            },
            {
              id: 'zipCode',
              type: 'text',
              label: 'ZIP/Postal Code',
              required: false,
              maxLength: 10,
              pdfField: 'Pt4Line7e_ZipCode',
            },
            {
              id: 'country',
              type: 'text',
              label: 'Country',
              required: true,
              maxLength: 30,
              pdfField: 'Pt4Line7f_Country',
            },
          ],
        },
        {
          id: 'birthInfo',
          title: '{{beneficiary.firstName}}\'s Birth Information',
          fallbackTitle: 'Beneficiary\'s Birth Information',
          fields: [
            {
              id: 'dateOfBirth',
              type: 'date',
              label: 'Date of Birth',
              required: true,
              pdfField: 'Pt4Line9_DateOfBirth',
            },
            {
              id: 'cityOfBirth',
              type: 'text',
              label: 'City/Town/Village of Birth',
              required: true,
              maxLength: 20,
              pdfField: 'Pt4Line10_CityOfBirth',
            },
            {
              id: 'countryOfBirth',
              type: 'text',
              label: 'Country of Birth',
              required: true,
              pdfField: 'Pt4Line11_CountryOfBirth',
            },
            {
              id: 'sex',
              type: 'radio',
              label: 'Sex',
              required: true,
              options: [
                { value: 'male', label: 'Male' },
                { value: 'female', label: 'Female' },
              ],
              pdfField: 'Pt4Line12_Sex',
            },
          ],
        },
        {
          id: 'citizenship',
          title: '{{beneficiary.firstName}}\'s Citizenship & Nationality',
          fallbackTitle: 'Beneficiary\'s Citizenship & Nationality',
          fields: [
            {
              id: 'nationality',
              type: 'text',
              label: 'Country of Citizenship or Nationality',
              required: true,
              pdfField: 'Pt4Line13_Citizenship',
            },
          ],
        },
        {
          id: 'maritalInfo',
          title: '{{beneficiary.firstName}}\'s Marital Information',
          fallbackTitle: 'Beneficiary\'s Marital Information',
          fields: [
            {
              id: 'maritalStatus',
              type: 'select',
              label: 'Current Marital Status',
              required: true,
              options: [
                { value: 'single', label: 'Single, Never Married' },
                { value: 'married', label: 'Married' },
                { value: 'divorced', label: 'Divorced' },
                { value: 'widowed', label: 'Widowed' },
                { value: 'separated', label: 'Legally Separated' },
                { value: 'annulled', label: 'Marriage Annulled' },
              ],
              pdfField: 'Pt4Line14_MaritalStatus',
            },
            {
              id: 'timesMarried',
              type: 'number',
              label: 'How many times has {{beneficiary.firstName}} been married?',
              fallbackLabel: 'How many times has the beneficiary been married?',
              nameInterpolation: true,
              required: true,
              pdfField: 'Pt4Line15_TimesMarried',
            },
          ],
        },
        {
          id: 'immigrationInfo',
          title: '{{beneficiary.firstName}}\'s Immigration Information',
          fallbackTitle: 'Beneficiary\'s Immigration Information',
          fields: [
            {
              id: 'inUS',
              type: 'radio',
              label: 'Is {{beneficiary.firstName}} currently in the United States?',
              fallbackLabel: 'Is the beneficiary currently in the United States?',
              nameInterpolation: true,
              required: true,
              options: [
                { value: 'yes', label: 'Yes' },
                { value: 'no', label: 'No' },
              ],
              pdfField: 'Pt4Line21_InUS',
            },
            {
              id: 'classOfAdmission',
              type: 'text',
              label: 'Class of Nonimmigrant Admission',
              required: false,
              helpText: 'e.g., B-2, F-1, H-1B',
              pdfField: 'Pt4Line22_ClassOfAdmission',
              conditionalDisplay: {
                field: 'part4.immigrationInfo.inUS',
                value: 'yes',
              },
            },
            {
              id: 'i94Number',
              type: 'text',
              label: 'I-94 Arrival-Departure Record Number',
              required: false,
              maxLength: 11,
              pdfField: 'Pt4Line23_I94Number',
              conditionalDisplay: {
                field: 'part4.immigrationInfo.inUS',
                value: 'yes',
              },
            },
            {
              id: 'dateOfArrival',
              type: 'date',
              label: 'Date of Arrival',
              required: false,
              pdfField: 'Pt4Line24_DateOfArrival',
              conditionalDisplay: {
                field: 'part4.immigrationInfo.inUS',
                value: 'yes',
              },
            },
            {
              id: 'authorizedStayExpiration',
              type: 'date',
              label: 'Date Authorized Stay Expires or D/S',
              required: false,
              pdfField: 'Pt4Line25_AuthorizedStayExpiration',
              conditionalDisplay: {
                field: 'part4.immigrationInfo.inUS',
                value: 'yes',
              },
            },
            {
              id: 'passportNumber',
              type: 'text',
              label: 'Passport Number',
              required: false,
              maxLength: 20,
              pdfField: 'Pt4Line26_PassportNumber',
            },
            {
              id: 'travelDocumentNumber',
              type: 'text',
              label: 'Travel Document Number',
              required: false,
              maxLength: 20,
              pdfField: 'Pt4Line27_TravelDocNumber',
            },
            {
              id: 'passportCountry',
              type: 'text',
              label: 'Country of Issuance for Passport/Travel Document',
              required: false,
              pdfField: 'Pt4Line28_PassportCountry',
            },
            {
              id: 'passportExpiration',
              type: 'date',
              label: 'Expiration Date for Passport/Travel Document',
              required: false,
              pdfField: 'Pt4Line29_PassportExpiration',
            },
          ],
        },
        {
          id: 'employmentInfo',
          title: '{{beneficiary.firstName}}\'s Current Employment',
          fallbackTitle: 'Beneficiary\'s Current Employment',
          fields: [
            {
              id: 'employerName',
              type: 'text',
              label: 'Name of Current Employer (if any)',
              required: false,
              maxLength: 45,
              pdfField: 'Pt4Line31_EmployerName',
            },
            {
              id: 'employerStreet',
              type: 'text',
              label: 'Employer Street Address',
              required: false,
              maxLength: 45,
              pdfField: 'Pt4Line32a_EmployerStreet',
            },
            {
              id: 'employerCity',
              type: 'text',
              label: 'Employer City',
              required: false,
              maxLength: 20,
              pdfField: 'Pt4Line32b_EmployerCity',
            },
            {
              id: 'employerState',
              type: 'text',
              label: 'Employer State/Province',
              required: false,
              maxLength: 20,
              pdfField: 'Pt4Line32c_EmployerState',
            },
            {
              id: 'employerCountry',
              type: 'text',
              label: 'Employer Country',
              required: false,
              maxLength: 30,
              pdfField: 'Pt4Line32d_EmployerCountry',
            },
          ],
        },
        {
          id: 'parentInfo',
          title: '{{beneficiary.firstName}}\'s Parent Information',
          fallbackTitle: 'Beneficiary\'s Parent Information',
          description: 'Provide information about {{beneficiary.firstName}}\'s parents.',
          fallbackDescription: 'Provide information about the beneficiary\'s parents.',
          fields: [
            {
              id: 'motherFamilyName',
              type: 'text',
              label: 'Mother\'s Family Name (Last Name)',
              required: false,
              maxLength: 33,
              pdfField: 'Pt4Line36a_MotherFamilyName',
            },
            {
              id: 'motherGivenName',
              type: 'text',
              label: 'Mother\'s Given Name (First Name)',
              required: false,
              maxLength: 33,
              pdfField: 'Pt4Line36b_MotherGivenName',
            },
            {
              id: 'motherMiddleName',
              type: 'text',
              label: 'Mother\'s Middle Name',
              required: false,
              maxLength: 33,
              pdfField: 'Pt4Line36c_MotherMiddleName',
            },
            {
              id: 'motherDateOfBirth',
              type: 'date',
              label: 'Mother\'s Date of Birth',
              required: false,
              pdfField: 'Pt4Line37_MotherDOB',
            },
            {
              id: 'motherCountryOfBirth',
              type: 'text',
              label: 'Mother\'s Country of Birth',
              required: false,
              pdfField: 'Pt4Line39_MotherCountryOfBirth',
            },
            {
              id: 'fatherFamilyName',
              type: 'text',
              label: 'Father\'s Family Name (Last Name)',
              required: false,
              maxLength: 33,
              pdfField: 'Pt4Line41a_FatherFamilyName',
            },
            {
              id: 'fatherGivenName',
              type: 'text',
              label: 'Father\'s Given Name (First Name)',
              required: false,
              maxLength: 33,
              pdfField: 'Pt4Line41b_FatherGivenName',
            },
            {
              id: 'fatherMiddleName',
              type: 'text',
              label: 'Father\'s Middle Name',
              required: false,
              maxLength: 33,
              pdfField: 'Pt4Line41c_FatherMiddleName',
            },
            {
              id: 'fatherDateOfBirth',
              type: 'date',
              label: 'Father\'s Date of Birth',
              required: false,
              pdfField: 'Pt4Line42_FatherDOB',
            },
            {
              id: 'fatherCountryOfBirth',
              type: 'text',
              label: 'Father\'s Country of Birth',
              required: false,
              pdfField: 'Pt4Line44_FatherCountryOfBirth',
            },
          ],
        },
        {
          id: 'proceedings',
          title: 'Prior Immigration Proceedings',
          fields: [
            {
              id: 'inProceedings',
              type: 'radio',
              label: 'Has {{beneficiary.firstName}} ever been in immigration proceedings?',
              fallbackLabel: 'Has the beneficiary ever been in immigration proceedings?',
              nameInterpolation: true,
              required: true,
              helpText: 'This includes removal, exclusion, rescission, or deportation proceedings.',
              options: [
                { value: 'no', label: 'No' },
                { value: 'yes_removal', label: 'Yes - Removal' },
                { value: 'yes_exclusion', label: 'Yes - Exclusion/Deportation' },
                { value: 'yes_rescission', label: 'Yes - Rescission' },
              ],
              pdfField: 'Pt4Line51_InProceedings',
            },
          ],
        },
        {
          id: 'processingChoice',
          title: 'Processing Information',
          description: 'You MUST select either Option 61 or Option 62, but NOT both.',
          fields: [
            {
              id: 'processingType',
              type: 'radio',
              label: 'How will {{beneficiary.firstName}} obtain permanent residence?',
              fallbackLabel: 'How will the beneficiary obtain permanent residence?',
              nameInterpolation: true,
              required: true,
              helpText: 'Select adjustment of status if {{beneficiary.firstName}} is in the U.S., or consular processing if {{beneficiary.firstName}} is abroad.',
              fallbackHelpText: 'Select adjustment of status if the beneficiary is in the U.S., or consular processing if they are abroad.',
              options: [
                { value: 'adjustment', label: 'Adjustment of Status in the United States (Item 61)' },
                { value: 'consular', label: 'Immigrant Visa at a U.S. Embassy/Consulate Abroad (Item 62)' },
              ],
              pdfField: 'Pt4Line61_ProcessingType',
            },
            {
              id: 'consulateCity',
              type: 'text',
              label: 'U.S. Embassy or Consulate City',
              required: false,
              maxLength: 30,
              pdfField: 'Pt4Line62a_ConsulateCity',
              conditionalDisplay: {
                field: 'part4.processingChoice.processingType',
                value: 'consular',
              },
            },
            {
              id: 'consulateCountry',
              type: 'text',
              label: 'U.S. Embassy or Consulate Country',
              required: false,
              maxLength: 30,
              pdfField: 'Pt4Line62b_ConsulateCountry',
              conditionalDisplay: {
                field: 'part4.processingChoice.processingType',
                value: 'consular',
              },
            },
          ],
        },
      ],
    },

    // =============================================
    // PART 5: Other Information
    // =============================================
    {
      id: 'part5',
      title: 'Part 5. Other Information',
      sections: [
        {
          id: 'otherInfo',
          title: 'Additional Information About {{beneficiary.firstName}}',
          fallbackTitle: 'Additional Information About Beneficiary',
          fields: [
            {
              id: 'inRemovalProceedings',
              type: 'radio',
              label: 'Is {{beneficiary.firstName}} currently in removal, deportation, or rescission proceedings?',
              fallbackLabel: 'Is the beneficiary currently in removal, deportation, or rescission proceedings?',
              nameInterpolation: true,
              required: true,
              options: [
                { value: 'yes', label: 'Yes' },
                { value: 'no', label: 'No' },
              ],
              pdfField: 'Pt5Line1_InRemoval',
            },
            {
              id: 'previouslyInUS',
              type: 'radio',
              label: 'Has {{beneficiary.firstName}} ever been in the United States?',
              fallbackLabel: 'Has the beneficiary ever been in the United States?',
              nameInterpolation: true,
              required: true,
              options: [
                { value: 'yes', label: 'Yes' },
                { value: 'no', label: 'No' },
              ],
              pdfField: 'Pt5Line2_PreviouslyInUS',
            },
            {
              id: 'arrested',
              type: 'radio',
              label: 'Has {{beneficiary.firstName}} ever been arrested, cited, charged, or convicted of any crime?',
              fallbackLabel: 'Has the beneficiary ever been arrested, cited, charged, or convicted of any crime?',
              nameInterpolation: true,
              required: true,
              options: [
                { value: 'yes', label: 'Yes' },
                { value: 'no', label: 'No' },
              ],
              pdfField: 'Pt5Line3_Arrested',
            },
            {
              id: 'previouslyApplied',
              type: 'radio',
              label: 'Has {{beneficiary.firstName}} previously applied for permanent residence?',
              fallbackLabel: 'Has the beneficiary previously applied for permanent residence?',
              nameInterpolation: true,
              required: true,
              options: [
                { value: 'yes', label: 'Yes' },
                { value: 'no', label: 'No' },
              ],
              pdfField: 'Pt5Line4_PreviouslyApplied',
            },
            {
              id: 'workedWithoutAuth',
              type: 'radio',
              label: 'Has {{beneficiary.firstName}} ever worked in the United States without authorization?',
              fallbackLabel: 'Has the beneficiary ever worked in the United States without authorization?',
              nameInterpolation: true,
              required: true,
              options: [
                { value: 'yes', label: 'Yes' },
                { value: 'no', label: 'No' },
              ],
              pdfField: 'Pt5Line5_WorkedWithoutAuth',
            },
            {
              id: 'additionalDetails',
              type: 'textarea',
              label: 'If you answered "Yes" to any question above, provide details',
              required: false,
              placeholder: 'Provide details about any "Yes" answers above...',
              pdfField: 'Pt5Line6_AdditionalDetails',
            },
          ],
        },
      ],
    },

    // =============================================
    // PART 6: Petitioner's Statement & Signature
    // =============================================
    {
      id: 'part6',
      title: 'Part 6. {{petitioner.firstName}}\'s Statement',
      fallbackTitle: 'Part 6. Petitioner\'s Statement',
      sections: [
        {
          id: 'statement',
          title: '{{petitioner.firstName}}\'s Statement, Contact, and Signature',
          fallbackTitle: 'Petitioner\'s Statement, Contact, and Signature',
          description: 'Select the appropriate statement and provide {{petitioner.firstName}}\'s contact information.',
          fallbackDescription: 'Select the appropriate statement and provide your contact information.',
          fields: [
            {
              id: 'canReadEnglish',
              type: 'radio',
              label: '{{petitioner.firstName}} can read and understand English, and has read and understood every question and instruction on this petition.',
              fallbackLabel: 'I can read and understand English, and I have read and understand every question and instruction on this petition.',
              nameInterpolation: true,
              required: true,
              options: [
                { value: 'yes', label: 'Yes, {{petitioner.firstName}} can read and understand English' },
                { value: 'no', label: 'No, an interpreter assisted {{petitioner.firstName}}' },
              ],
              fallbackOptions: [
                { value: 'yes', label: 'Yes, I can read and understand English' },
                { value: 'no', label: 'No, an interpreter assisted me' },
              ],
              pdfField: 'Pt6Line1_CanReadEnglish',
            },
            {
              id: 'interpreterLanguage',
              type: 'text',
              label: 'Language of the interpreter',
              required: false,
              maxLength: 30,
              pdfField: 'Pt6Line1b_InterpreterLanguage',
              conditionalDisplay: {
                field: 'part6.statement.canReadEnglish',
                value: 'no',
              },
            },
            {
              id: 'preparerUsed',
              type: 'radio',
              label: 'Did someone other than {{petitioner.firstName}} prepare this petition?',
              fallbackLabel: 'Did someone other than you prepare this petition?',
              nameInterpolation: true,
              required: true,
              options: [
                { value: 'yes', label: 'Yes' },
                { value: 'no', label: 'No, {{petitioner.firstName}} prepared it' },
              ],
              fallbackOptions: [
                { value: 'yes', label: 'Yes' },
                { value: 'no', label: 'No, I prepared it myself' },
              ],
              pdfField: 'Pt6Line2_PreparerUsed',
            },
            {
              id: 'daytimePhone',
              type: 'phone',
              label: '{{petitioner.firstName}}\'s Daytime Telephone Number',
              fallbackLabel: 'Petitioner\'s Daytime Telephone Number',
              nameInterpolation: true,
              required: true,
              pdfField: 'Pt6Line5_DaytimePhone',
            },
            {
              id: 'mobilePhone',
              type: 'phone',
              label: '{{petitioner.firstName}}\'s Mobile Telephone Number',
              fallbackLabel: 'Petitioner\'s Mobile Telephone Number',
              nameInterpolation: true,
              required: false,
              pdfField: 'Pt6Line6_MobilePhone',
            },
            {
              id: 'email',
              type: 'email',
              label: '{{petitioner.firstName}}\'s Email Address',
              fallbackLabel: 'Petitioner\'s Email Address',
              nameInterpolation: true,
              required: false,
              pdfField: 'Pt6Line7_Email',
            },
          ],
        },
      ],
    },

    // =============================================
    // PART 7: Interpreter's Contact Information
    // =============================================
    {
      id: 'part7',
      title: 'Part 7. Interpreter\'s Information',
      sections: [
        {
          id: 'interpreter',
          title: 'Interpreter\'s Contact Information',
          description: 'Complete this section only if an interpreter assisted the petitioner.',
          fields: [
            {
              id: 'interpreterFamilyName',
              type: 'text',
              label: 'Interpreter\'s Family Name (Last Name)',
              required: false,
              maxLength: 33,
              pdfField: 'Pt7Line1a_InterpreterFamilyName',
              conditionalDisplay: {
                field: 'part6.statement.canReadEnglish',
                value: 'no',
              },
            },
            {
              id: 'interpreterGivenName',
              type: 'text',
              label: 'Interpreter\'s Given Name (First Name)',
              required: false,
              maxLength: 33,
              pdfField: 'Pt7Line1b_InterpreterGivenName',
              conditionalDisplay: {
                field: 'part6.statement.canReadEnglish',
                value: 'no',
              },
            },
            {
              id: 'interpreterBusinessName',
              type: 'text',
              label: 'Interpreter\'s Business or Organization Name',
              required: false,
              maxLength: 45,
              pdfField: 'Pt7Line2_InterpreterBusiness',
              conditionalDisplay: {
                field: 'part6.statement.canReadEnglish',
                value: 'no',
              },
            },
            {
              id: 'interpreterPhone',
              type: 'phone',
              label: 'Interpreter\'s Daytime Telephone Number',
              required: false,
              pdfField: 'Pt7Line6_InterpreterPhone',
              conditionalDisplay: {
                field: 'part6.statement.canReadEnglish',
                value: 'no',
              },
            },
            {
              id: 'interpreterEmail',
              type: 'email',
              label: 'Interpreter\'s Email Address',
              required: false,
              pdfField: 'Pt7Line8_InterpreterEmail',
              conditionalDisplay: {
                field: 'part6.statement.canReadEnglish',
                value: 'no',
              },
            },
            {
              id: 'interpreterLanguage',
              type: 'text',
              label: 'Language Interpreted',
              required: false,
              maxLength: 30,
              pdfField: 'Pt7Line9_InterpreterLanguage',
              conditionalDisplay: {
                field: 'part6.statement.canReadEnglish',
                value: 'no',
              },
            },
          ],
        },
      ],
    },

    // =============================================
    // PART 8: Preparer's Contact Information
    // =============================================
    {
      id: 'part8',
      title: 'Part 8. Preparer\'s Information',
      sections: [
        {
          id: 'preparer',
          title: 'Preparer\'s Contact Information',
          description: 'Complete this section only if someone other than the petitioner prepared this petition.',
          fields: [
            {
              id: 'preparerFamilyName',
              type: 'text',
              label: 'Preparer\'s Family Name (Last Name)',
              required: false,
              maxLength: 33,
              pdfField: 'Pt8Line1a_PreparerFamilyName',
              conditionalDisplay: {
                field: 'part6.statement.preparerUsed',
                value: 'yes',
              },
            },
            {
              id: 'preparerGivenName',
              type: 'text',
              label: 'Preparer\'s Given Name (First Name)',
              required: false,
              maxLength: 33,
              pdfField: 'Pt8Line1b_PreparerGivenName',
              conditionalDisplay: {
                field: 'part6.statement.preparerUsed',
                value: 'yes',
              },
            },
            {
              id: 'preparerBusinessName',
              type: 'text',
              label: 'Preparer\'s Business or Organization Name',
              required: false,
              maxLength: 45,
              pdfField: 'Pt8Line2_PreparerBusiness',
              conditionalDisplay: {
                field: 'part6.statement.preparerUsed',
                value: 'yes',
              },
            },
            {
              id: 'preparerPhone',
              type: 'phone',
              label: 'Preparer\'s Daytime Telephone Number',
              required: false,
              pdfField: 'Pt8Line6_PreparerPhone',
              conditionalDisplay: {
                field: 'part6.statement.preparerUsed',
                value: 'yes',
              },
            },
            {
              id: 'preparerEmail',
              type: 'email',
              label: 'Preparer\'s Email Address',
              required: false,
              pdfField: 'Pt8Line8_PreparerEmail',
              conditionalDisplay: {
                field: 'part6.statement.preparerUsed',
                value: 'yes',
              },
            },
            {
              id: 'isAttorney',
              type: 'checkbox',
              label: 'I am an attorney or accredited representative.',
              required: false,
              pdfField: 'Pt8Line9_IsAttorney',
              conditionalDisplay: {
                field: 'part6.statement.preparerUsed',
                value: 'yes',
              },
            },
          ],
        },
      ],
    },
  ],
};
